#!/usr/bin/env bash
#
# Regenerate ops/nginx/cloudflare-realip.conf from Cloudflare's published edge ranges.
#
# Run it from anywhere; it writes next to itself and leaves nginx alone — reloading is a
# separate, deliberate act because a bad fetch must not be able to take the site down:
#
#   sudo ops/nginx/refresh-cloudflare-ips.sh
#   sudo nginx -t && sudo systemctl reload nginx
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${HERE}/cloudflare-realip.conf"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

fetch() {
  curl --fail --silent --show-error --location --max-time 20 "$1"
}

v4="$(fetch https://www.cloudflare.com/ips-v4)"
v6="$(fetch https://www.cloudflare.com/ips-v6)"

# A truncated or error-page response would otherwise be written straight over a working file.
if [ "$(printf '%s\n' "$v4" | grep -c '/')" -lt 5 ] || [ "$(printf '%s\n' "$v6" | grep -c '/')" -lt 3 ]; then
  echo "refresh-cloudflare-ips: response did not look like an IP list; keeping existing file" >&2
  exit 1
fi

{
  echo "# Cloudflare edge ranges — trusted sources for the CF-Connecting-IP header."
  echo "#"
  echo "# GENERATED by ops/nginx/refresh-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# Do not edit by hand."
  echo
  printf '%s\n' "$v4" | sed '/^[[:space:]]*$/d;s#^#set_real_ip_from #;s#$#;#'
  echo
  printf '%s\n' "$v6" | sed '/^[[:space:]]*$/d;s#^#set_real_ip_from #;s#$#;#'
  echo
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive off;"
} >"$TMP"

install -m 0644 "$TMP" "$OUT"
echo "refresh-cloudflare-ips: wrote $OUT"
